Improve `Amount` and `Currency`
sephynox/xrpl-rust pull request #55
Opened 2023-03-14 22:00 UTC by LimpidCrypto

## High Level Overview of Change
### Model conversion
This PR changes the lifetime of `Currency` and `Amount` from `'static` to `'a`. It also adds `to_amount` to turn a `Currency` into an `Amount` giving a `value`. Implement the  `From<Amount> for Currency` trait to turn an `Amount` into a `Currency`.

### `value` conversion
The `get_value_as_u32` method was also replaced with `TryInto<rust_decimal::Decimal> for Amount` to have a more convenient way to deal with an `Amount.value`. The `get_value_as_u32` also don't make sense for `IssuedCurrencyAmount` since it's `value` is most likely a decimal value.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Future Tasks
- [ ] Add errors as soon as #54 was merged.

2023-03-15 03:13 UTC, sephynox requested changes

2023-03-15 03:13 UTC, sephynox commented on src/models/transactions/nftoken_accept_offer.rs
> +                let as_decimal: Decimal = nftoken_broker_fee.clone().try_into().unwrap();
This is an unhandled `try_into` and `unwrap`.

2023-03-15 03:13 UTC, sephynox commented on src/models/transactions/nftoken_accept_offer.rs
> +                }
We can just use if/else blocks for booleans.

2023-03-15 03:13 UTC, sephynox commented on src/models/transactions/nftoken_create_offer.rs
>              false => Ok(()),
We should use if/else blocks for booleans.

2023-03-15 03:13 UTC, sephynox commented on src/models/transactions/nftoken_create_offer.rs
> +        let amount_as_decimal: Decimal = self.amount.clone().try_into().unwrap();
This is an unhandled `try_into` and `unwrap`.

2023-03-17 17:29 UTC, LimpidCrypto commented
Honestly I think it might be better if we had separate models for `XRP` and `IssuedCurrency` as currencies and `XRPAmount` and `IssuedCurrencyAmount` as amounts. That enables us to make our library to be stronger typed. Like an `AccountRoot` objects `Balance` could only be `XRPAmount`.

What's your opinion @sephynox ?
If you agree I would close the PR.

2023-03-17 20:01 UTC, closed without merging